name: icons_explorer
description: A sample command-line application that display your SVGs in you browser.
version: 1.0.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  args: ^2.4.1
  path: ^1.8.3
